### PR TITLE
Make docs accessible only to users with cloak repo access

### PR DESCRIPTION
**Pull request by slumbering**
Signed-off-by: jffarge <jf@dagger.io>

### CODE REVIEW

**Review by aluzzardi — APPROVED** [review]
@slumbering good to merge?

**Comment by aluzzardi** [comment]
This repository has moved to https://github.com/dagger/dagger/tree/cloak

Please re-open this PR in `dagger/dagger`:

From the cloak repository:

1) Fetch dagger/dagger

```
git remote add dagger git@github.com:dagger/dagger.git
git fetch --all
```

2) [optional but recommended] Duplicate your branch

```
git checkout your-pr-branch
git checkout -b your-pr-branch-copy
```

3) Rebase your branch on top of dagger/dagger's cloak branch

NOTE: there might be some commits not authored by you. Delete them.

```
git rebase -i dagger/cloak
```

4) Update your local cloak repo to be downstream of your dagger fork

```
git remote set-url origin git@github.com:<your_username>/dagger.git
git push --set-upstream origin your-pr-branch-copy
```

5) Re-create PR in dagger/dagger

Make sure you have the GitHub CLI installed (on macOS: `brew install gh`)

```
gh pr create -R dagger/dagger --base cloak
```

6) Close PR in dagger/cloak

**Comment by slumbering** [comment]
PR moved to dagger/dagger repo

**Comment by slumbering** [comment]
PR moved to dagger/dagger repo

**Pull request closed without merging**
